import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


import Profile from '@/components/Profile/Profile'
import UpdateDescription from '@/components/Profile/Description'
import prisma from '@/lib/prisma'
import { getSession, useSession } from 'next-auth/react'

import { useRouter } from 'next/router'
// import { SafeJson } from './lib/formatHelpers'


const inter = Inter({ subsets: ['latin'] })

export default function Home({post}) {

  const router = useRouter()
  const session = useSession()
  if(session.status === 'unauthenticated') 
  {
    router.replace('/Blog')
  } else if (session.status === 'authenticated') {

    
    return (
      <>
      <Head>
        <title>Controllex</title>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <div>
      </div>    
     
      
    <h1>
      </h1>  
      <Profile Post={post.Post} data={post}/>
              </main>
    </>
  )
}
}

export const getServerSideProps = async ({params}) =>{
  

    let  data = await  prisma.user.findUnique({
      where:{
        id: params.id
      },
      include:{
        Post: true,
        Archives: true
      }
    })
    
    
    const serializedData = JSON.stringify(data);
    const safeData = JSON.parse(serializedData);   
    console.log(safeData)
    return{ props: {
      post: safeData,
    }}
  
  }